remote_theme: "jekyll-theme-minimal-resume"

# Site settings
title: Lit Phansiri
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lit Phansiri
user_description: Qualified technology and military leader with more than 16 years of experience. Objective is to continue working with and building high energy, high value teams to study, design and develop information technology solutions for the good of people, organizations, and society. Talent and passion for finding creative solutions to complex problems while developing information technology to win. Hands on leader with an intimate knowledge of technology, tools, and people. 
user_title: Marine Corps Officer / Software Engineer
email: lphansiri@gmail.com
# twitter_username: lorem_ipsum
github_username:  phansiri
linkedin_username: litthideth-phansiri-6b79b098
# gplus_username:  lorem_ipsum

# Google-analytics
# google-analytics:
#   id: ""

# exclude: ['package.json', 'src' , 'node_modules']
